-- MySQL Script generated by MySQL Workbench
-- Thu Oct 17 15:35:18 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Course` (
  `course_number` INT NOT NULL,
  `title` VARCHAR(255) NULL,
  `credits` INT NULL,
  `Syllabus` VARCHAR(255) NULL,
  `prerequisites` VARCHAR(255) NULL,
  PRIMARY KEY (`course_number`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Instructor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Instructor` (
  `instructor_id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `department` VARCHAR(100) NULL,
  `title` VARCHAR(100) NULL,
  `` VARCHAR(45) NULL,
  PRIMARY KEY (`instructor_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CourseOffering`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CourseOffering` (
  `offering_id` INT NOT NULL AUTO_INCREMENT,
  `course_number` INT NULL,
  `year` INT NULL,
  `Semester` INT NULL,
  `Section_no` INT NULL,
  `instructor_id` INT NULL,
  `Timings` TIME NULL,
  `classroom` VARCHAR(45) NULL,
  PRIMARY KEY (`offering_id`),
  INDEX `fk_courseOffering_1_idx` (`course_number` ASC) VISIBLE,
  INDEX `fk_CourseOffering_2_idx` (`instructor_id` ASC) VISIBLE,
  CONSTRAINT `fk_courseOffering_1`
    FOREIGN KEY (`course_number`)
    REFERENCES `mydb`.`Course` (`course_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CourseOffering_2`
    FOREIGN KEY (`instructor_id`)
    REFERENCES `mydb`.`Instructor` (`instructor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Student` (
  `student_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `program` VARCHAR(100) NULL,
  PRIMARY KEY (`student_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Enrollment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Enrollment` (
  `enrollment_id` INT NOT NULL,
  `student_id` INT NULL,
  `offering_id` INT NULL,
  `grade` CHAR(2) NULL,
  PRIMARY KEY (`enrollment_id`),
  INDEX `fk_Enrollment_1_idx` (`student_id` ASC) VISIBLE,
  INDEX `fk_Enrollment_2_idx` (`offering_id` ASC) VISIBLE,
  CONSTRAINT `fk_Enrollment_1`
    FOREIGN KEY (`student_id`)
    REFERENCES `mydb`.`Student` (`student_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Enrollment_2`
    FOREIGN KEY (`offering_id`)
    REFERENCES `mydb`.`CourseOffering` (`offering_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
